// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_m3DrdESJACb_ocJrMmc9TxhmDSLd0j8',
    appId: '1:523793881936:web:2ae90fd7c27fa51d422a55',
    messagingSenderId: '523793881936',
    projectId: 'noteapp-f45fd',
    authDomain: 'noteapp-f45fd.firebaseapp.com',
    storageBucket: 'noteapp-f45fd.firebasestorage.app',
    measurementId: 'G-PPHKD5N535',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9yotyfqVgLE0FgDksdYFPswdx9pTPZgU',
    appId: '1:523793881936:android:f9b9ce1c086227fe422a55',
    messagingSenderId: '523793881936',
    projectId: 'noteapp-f45fd',
    storageBucket: 'noteapp-f45fd.firebasestorage.app',
  );
}
